services:
  comfyui:
    image: ghcr.io/therobrary/comfyui-docker-build:latest
    container_name: comfyui-prebuilt
    ports:
      - "8188:8188"
    volumes:
      # Mount model directories for persistence
      - ./models:/app/ComfyUI/models
      - ./input:/app/ComfyUI/input
      - ./output:/app/ComfyUI/output
      - ./custom_nodes:/app/ComfyUI/custom_nodes
      # Optional: Mount additional custom nodes
      - ./extra_model_paths.yaml:/app/ComfyUI/extra_model_paths.yaml
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    command: ["--listen", "0.0.0.0", "--port", "8188", "--preview-method", "auto", "--gpu-only"]